name: dsfda
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_analytics: ^10.1.6
  cloud_functions: ^4.0.13
  firebase_app_check: ^0.1.1
  firebase_messaging: ^14.3.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  firebase_database: ^10.0.16
  firebase_performance: ^0.9.0
  firebase_crashlytics: ^3.0.17
  firebase_core: ^2.8.0
  diamond_bottom_bar: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3
  lottie: ^2.6.0
  badges: ^3.1.1
  smooth_page_indicator: ^1.1.0
  loop_page_view: ^1.2.5
  zego_uikit_prebuilt_live_audio_room: ^2.11.2
  zego_zim: ^2.10.0+4
  zego_uikit_prebuilt_live_streaming: ^2.19.0
  zego_express_engine: any
  permission_handler: any
  http: ^0.13.4
  flutter_styled_toast: ^2.1.3
  statemachine: ^3.2.0
  flutter_screenutil: ">=5.5.3+2 <5.6.1"
  cached_network_image: ^3.2.3
  zego_uikit: ^2.12.0
  zego_uikit_signaling_plugin: ^2.5.0
  image_picker: ^1.0.4
  file_picker: ^5.5.0


flutter:
  uses-material-design: true

assets:
    - images/
    - assets/images/image4.png
    - assets/images/15.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
